modified to send failed result as well

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,35 +1,55 @@
 version: 2.1
+
 jobs:
   run-test:
     docker:
       - image: mcr.microsoft.com/playwright:v1.35.0-jammy
-    # Steps to the job
+    # Steps for the job
     steps:
       - checkout
       - run: npm ci
       - run:
-          name: Run test
+          name: Run tests
           command: npx playwright test --grep=@smoke
+          no_output_timeout: 10m
+          environment:
+            NO_COLOR: "1"
+
       - run:
-          name: Report Results
+          name: Process test results
           command: |
-            # Report the test results back to the react-portfolio-app repository
-            curl -X POST https://api.github.com/repos/AndriiFrolov/react-portfolio-app/statuses/$CIRCLE_SHA1 \
-              -H "Authorization: Bearer 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" \
-              -H "Content-Type: application/json" \
-              -d '{
-                "state": "success",
-                "context": "circleci/tests",
-                "description": "Tests passed successfully"
-                
+            if [ $? -eq 0 ]; then
+              # All tests passed
+              curl -X POST https://api.github.com/repos/AndriiFrolov/react-portfolio-app/statuses/$CIRCLE_SHA1 \
+                -H "Authorization: Bearer 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" \
+                -H "Content-Type: application/json" \
+                -d '{
+                  "state": "success",
+                  "context": "circleci/tests",
+                  "description": "All tests passed"
+                }'
+            else
+              # At least one test failed
+              curl -X POST https://api.github.com/repos/AndriiFrolov/react-portfolio-app/statuses/$CIRCLE_SHA1 \
+                -H "Authorization: Bearer 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" \
+                -H "Content-Type: application/json" \
+                -d '{
+                  "state": "failure",
+                  "context": "circleci/tests",
+                  "description": "Some tests failed"
+                }'
+              exit 1
+          when: always
+
       - store_test_results:
           path: ./outcome/test-results/results.xml
 
-      - store_artifacts:
-          path: ./allure-results/
+      # - store_artifacts:
+      #     path: ./allure-results/
 
       - store_artifacts:
           path: ./outcome/html
+
 # Invoke jobs via workflows
 workflows:
   run-test-workflow:
